name: pipe2drive
version: '0.1.0'
summary: Pipe your data to Google Drive
description: |
  If you pipe data (doesn't matter what data) to this program and then select a name for that data and declare it size, it will be uploaded to Google Drive.
  pipe2drive is a simple program I wrote for myself, because I wanted a way to create a tarball of my files and upload them to Google Drive without having to store the tarball on my system. I didn't want to store the tarball on my system because that would require around as much free space as the data itself, since it wasn't compressible.

base: core18
grade: stable
confinement: strict


parts:
  pipe2drive:
    plugin: rust
    override-build: |
      [ -f "$SNAPCRAFT_PART_INSTALL/bin/${SNAP_NAME}" ] && rm "$SNAPCRAFT_PART_INSTALL/bin/${SNAP_NAME}"
      snapcraftctl build

    source: .
    stage-packages:
      - libssl-dev
      - pkg-config

apps:
  pipe2drive:
    command: bin/pipe2drive
    environment:
            HOME: ${SNAP_USER_COMMON}

