name: Run Unittests 

run-name: ${{ github.actor }} is running unittests 🚀

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 3 * * *'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cargo - Run Unittests
        uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
          PIPE2DRIVE_CLIENT_SECRET_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_SECRET_DATA }}
          PIPE2DRIVE_CLIENT_TOKEN_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_TOKEN_DATA }}
        with:
          command: test
          args: -- --test-threads=1 --nocapture

      - name: Upload configs from pipe2drive created by unittests
        uses: actions/upload-artifact@v3
        with:
          name: pipe2drive-config-folder-from-host-system
          path: ~/.config/pipe2drive

  snapcraft:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
    steps:
      - uses: actions/checkout@v3

#      - name: Build snap
#        uses: snapcore/action-build@v1
#        id: snapcraft

      - name: Build snap
        uses: diddlesnaps/snapcraft-multiarch-action@v1.7.0
        id: snapcraft
        with:
          architecture: ${{ matrix.platform }}

      - name: Upload snap as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: pipe2drive.${{ matrix.arch }}.snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Search for the Mozilla root certificate on the host system
        run: find /var/ssl /usr/share/ssl /usr/local/ssl /usr/local/openssl /usr/local/etc/openssl /usr/local/share /usr/lib/ssl /usr/ssl /etc/openssl /etc/pki/ca-trust/extracted/pem /etc/pki/tls /etc/ssl /etc/certs /opt/etc/ssl /data/data/com.termux/files/usr/etc/tls /boot/system/data/ssl -type f \( -name cert.pem -o -name certs.pem -o -name ca-bundle.pem -o -name cacert.pem -o -name ca-certificates.crt -o -name ca-certificates.crt -o -name ca-root-nss.crt -o -name ca-bundle.crt -o -name CARootCertificates.pem -o -name tls-ca-bundle.pem \) -ls || true

      - name: Install the snap package pipe2drive
        run: sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}

      - name: Show sorted list of all environment variables in the snap - pipe2drive
        run: echo env | snap run --shell pipe2drive | sort

      - name: Search for the Mozilla root certificate in the snap - pipe2drive
        run: echo 'find /var/ssl /usr/share/ssl /usr/local/ssl /usr/local/openssl /usr/local/etc/openssl /usr/local/share /usr/lib/ssl /usr/ssl /etc/openssl /etc/pki/ca-trust/extracted/pem /etc/pki/tls /etc/ssl /etc/certs /opt/etc/ssl /data/data/com.termux/files/usr/etc/tls /boot/system/data/ssl -type f \( -name cert.pem -o -name certs.pem -o -name ca-bundle.pem -o -name cacert.pem -o -name ca-certificates.crt -o -name ca-certificates.crt -o -name ca-root-nss.crt -o -name ca-bundle.crt -o -name CARootCertificates.pem -o -name tls-ca-bundle.pem \) -ls' | snap run --shell pipe2drive  || true

      - name: Run snap (pipe2drive) and upload unencrypted file
        env:
          RUST_BACKTRACE: 1
          PIPE2DRIVE_CLIENT_SECRET_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_SECRET_DATA }}
          PIPE2DRIVE_CLIENT_TOKEN_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_TOKEN_DATA }}
        run: snap run pipe2drive upload --replace --size 100mib --filename testing_snap_build_${{ matrix.arch }}.txt --testing --testing-size 90mib

      - name: Run snap (pipe2drive) and upload encrypted file
        env:
          RUST_BACKTRACE: 1
          PIPE2DRIVE_CLIENT_SECRET_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_SECRET_DATA }}
          PIPE2DRIVE_CLIENT_TOKEN_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_TOKEN_DATA }}
        run: snap run pipe2drive upload --replace --size 100mib --filename testing_snap_build_${{ matrix.arch }}_encrypted.txt --testing --testing-size 90mib

      - name: Upload configs from pipe2drive created by the snap
        uses: actions/upload-artifact@v3
        with:
          name: pipe2drive-config-folder-from-the-snap.${{ matrix.arch }}
          path: ~/snap/pipe2drive/common/.config/pipe2drive

      - name: Upload Snap (edge)
        if: ${{ github.ref_name == 'dev' }}
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge

      - name: Upload snapcraft log
        uses: actions/upload-artifact@v3
        if: ${{ github.ref_name == 'dev' }}
        with:
          name: pipe2drive-snap-upload-log.${{ matrix.arch }}
          path: ~/.cache/snapcraft/log

  merge-dev-to-main-branch:
    needs: [unittest,snapcraft]
    if : ${{ github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version set in snapcraft.yaml
        id: snapcraft-version
        uses: jbutcher5/read-yaml@main
        with:
          file: './snap/snapcraft.yaml'
          key-path: '["version"]'

      - name: Get the version set in Cargo.toml
        uses: dangdennis/toml-action@main
        id: cargo-version
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Find version tag
        id: get-tag-if-any
        uses: digital-ai/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD'
          exact-match: 'true'

      - name: Print out the version found in different locations
        run: >-
          echo " 
          snapcraft version: ${{ steps.snapcraft-version.outputs.data }}
          -
          cargo version: ${{ steps.cargo-version.outputs.value }}
          -
          tag: ${{ steps.get-tag-if-any.outputs.tag }}
          -
          ref_type: ${{ github.ref_type }}
          -
          ref_name: ${{ github.ref_name }}
          "

      - name: Make pull request to merge dev to main
        if: >-
          ${{ steps.get-tag-if-any.outputs.tag != 'NO_TAGS' && }}
              steps.get-tag-if-any.outputs.tag == format('v{0}', steps.snapcraft-version.outputs.data) && 
              steps.get-tag-if-any.outputs.tag == format('v{0}', steps.cargo-version.outputs.value) }}
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: main
          title: Merge dev to main and bump the version to ${{ steps.get-tag-if-any.outputs.tag }}"
          body: |
            This pull request was automatically created by GitHub Action.
            This pull request will merge dev to main and bump the version to ${{ steps.get-tag-if-any.outputs.tag }}.
          label: enhancement
          allow_no_diff: false
