name: Run Unittests 
run-name: ${{ github.actor }} is running unittests 🚀
on: [push, pull_request]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
          PIPE2DRIVE_CLIENT_SECRET_DATA: ${{ secrets.PIPE2DRIVE_CLIENT_SECRET_DATA }}
        with:
          command: test
          args: -- --test-threads=1 --nocapture
